version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.frontend.rule: "HostRegexp:${TRAEFIK_HOSTS}"
    restart: always
networks:
  web:
    external: true
