version: '3.5'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - traefik
    labels:
      traefik.enable: true
      traefik.frontend.rule: "HostRegexp:${TRAEFIK_HOSTS}"
    restart: unless-stopped
networks:
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true
